name: Publish to PyPI

on:
  push:
    tags:
      - "v*"     # runs when you push a tag like v0.1.2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # uncomment to do a dry run against TestPyPI first:
          # repository-url: https://test.pypi.org/legacy/
