name: Publish to PyPI (tag-driven)

on:
  push:
    tags:
      - "v*"          # e.g., v0.1.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build tomli tomli-w

      - name: Clean dist
        run: rm -rf dist

      - name: Derive version from tag and write into pyproject.toml
        run: |
          TAG="${GITHUB_REF_NAME}"              # e.g., v0.1.3
          VERSION="${TAG#v}"                    # strip leading 'v' -> 0.1.3
          python - << 'PY'
          import sys, pathlib
          import tomli, tomli_w

          p = pathlib.Path("pyproject.toml")
          data = tomli.loads(p.read_text(encoding="utf-8"))
          data.setdefault("project", {})
          data["project"]["version"] = sys.argv[1]
          p.write_text(tomli_w.dumps(data), encoding="utf-8")
          print("Set project.version =", sys.argv[1])
          PY
          "$VERSION"

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # skip-existing: true  # uncomment if you sometimes re-run the same tag
